### ISSUE TITLE
gstshark-plot : error: load_serie_timestamp_value: A(I,J,...) = X: dimensions mismatch

### ISSUE THREAD

**Issue by josejich** [RidgeRun/gst-shark#10]
Trying to use the graphics scripts gives the following error on ubuntu 14.04:
 
./gstshark-plot scheduletime -p 
Loading proctime events...
Loading interlatency events...
Loading scheduling events...
Loading cpuusage events...
Loading framerate events...
Processing proctime...
Processing interlatency...
Processing framerate...
Processing scheduling...
error: load_serie_timestamp_value: A(I,J,...) = X: dimensions mismatch
error: called from:
error:   /home/jjimenez/work/devdirs/Mayfield/gstreamer-1.8/build-core/gst-shark/scripts/graphics/load_serie_timestamp_value.m at line 85, column 65
error:   /home/jjimenez/work/devdirs/Mayfield/gstreamer-1.8/build-core/gst-shark/scripts/graphics/plot_scheduling.m at line 12, column 43
error:   /home/jjimenez/work/devdirs/Mayfield/gstreamer-1.8/build-core/gst-shark/scripts/graphics/gstshark-plot.m at line 38, column 13
octave:1> vim gstshark-plot
error: 'vim' undefined near line 1 column 1

octave --version
GNU Octave, version 3.8.1

**Comment by rrcarlosrodriguez** [comment]
This was fixed in the scheduletime and the interlatency plotting functionality. The problem was related to the type of variable used to store the timestamp of the log. We were using int variable and in some cases it was not enough and an overflow happened, so that we changed the variable to double to fix the issue.
